spring.application.name: sample

management.security.enabled: false

#logging.level: 
#  de.codecentric.boot.admin: DEBUG

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: xxxxxxxxxxxxx@gmail.com
    password: xxxxxxxxxxxxx
    properties:
      mail.smtp.auth: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

spring.boot.admin:
  notify:
    mail:
      enabled: false
  url: http://localhost:8080
  deploy:
#    bootstrap:
#      - foo
#      - bar
    charset: gbk
    mail:
      enabled: true
      simple-mail-message: 
        from: xxxxxxxxxxxxxxx@gmail.com
        to:
          - xxxxxxxxxxxxxxxxx@qq.com
        subject: test
        text: Hi, 
          
    actions:
      foo: 
        -
          exec: cd chun
          working-directory: C:\Users
      bar: 
        -
          exec: ping www.baidu.com
        -
          exec: ipconfig
