spring.application.name: sample

management.security.enabled: false

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: xxxxx@gmail.com
    password: xxxxx
    properties:
      mail.smtp.auth: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

spring.boot.admin:
  notify:
    mail:
      enabled: false
  url: http://localhost:8080
  deploy:
    bootstrap:
      - foo
      - bar
    charset: gbk
    mail:
      enabled: false
      simpleMailMessage:
        from: xxxxx@gmail.com
        to:
          - xxxx@qq.com
        subject: test
        text: Hi, 
          
    actions:
      foo: 
        -
          exec: ipconfig
      bar: 
        -
          exec: ping wwww.baidu.com
        -
          exec: ipconfig
