spring.application.name: a

spring.boot.admin:
  url: http://localhost:8080
  deploy:
    actions:
      foo: 
        -
          executable: ipconfig
      bar: 
        -
          executable: ping
          args:
            - wwww.baidu.com
